### Numpy Matrices

Numerical Python library has support for large, multi-dimensional `arrays and matrices`.  

### Vectors

A vector is `one-dimensional` array.

In [50]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1], 
              [4], 
              [3]])

print("Row vector:\n", a)
print("Column vector:\n", b)

Row vector:
 [1 2 3]
Column vector:
 [[1]
 [4]
 [3]]


### Matrices

Numpy's `main data structure` is the multidimensional array (matrix).

In [51]:
# matrix with three rows, four columns

A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])

print("Matrix:\n", A)
print("Shape:", A.shape)
print("Size:", A.size)
print("Number of array dimension:", A.ndim)

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Size: 12
Number of array dimension: 2


### Access Elements

The data elements in a matrix can be accessed by using [ : ] `slice notation` (up-to OR after).

In [52]:
a = np.array([1, 2, 3, 4, 5, 6])

print("a[:] =", a[:])           # entire range of elements
print("a[:3] =", a[:3])         # 0 to 3 (not included)
print("a[0:3] =", a[0:3])       # 0 to 3 (not included)
print("a[3:] =", a[3:])         # 3 (included) to last
print("a[-1] =", a[-1])         # last
print("a[3:-1] =", a[3:-1])     # 3 to last (not included)

a[:] = [1 2 3 4 5 6]
a[:3] = [1 2 3]
a[0:3] = [1 2 3]
a[3:] = [4 5 6]
a[-1] = 6
a[3:-1] = [4 5]


Arrays are `zero-indexed`, first element is 0

In [53]:
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])

print("A[1,1] =", A[1,1])       # second row, second column
print("A[:2, :] =", A[:2, :])   # 0 to 2 rows, all columns
print("A[:, 1:2] =", A[:, 1:2]) # all rows, second column

A[1,1] = 6
A[:2, :] = [[1 2 3 4]
 [5 6 7 8]]
A[:, 1:2] = [[ 2]
 [ 6]
 [10]]


### Sparse Matrices

A sparse matrix stores `only non-zero` elements, for computation savings.

In [54]:
from scipy import sparse

A = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], 
    [3, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
])
A_sparse = sparse.csr_matrix(A)

print("Sparce matrix:"); print(A_sparse)

Sparce matrix:
  (1, 1)	1
  (2, 0)	3


### Vectorization

Vectorization is used to `speed up` the Python code without using loop.  
Insteed of opertating on a single value at a time, it operates on a `set of value` (vector) at a time.

In [55]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
A_vectorized = np.vectorize(lambda x: x + 100)(A)

print("A vectorized:"); print(A_vectorized)

A vectorized:
[[101 102 103]
 [104 105 106]
 [107 108 109]]


### Broadcasting

Broadcasting allows Numpy to handle arrays of `different shapes` during arithmetic operations.